apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-challenge-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-challenge-api-service
  template:
    metadata:
      labels:
        app: node-challenge-api-service
    spec:
      containers:
        - name: node-challenge-api-service
          image: localhost:31111/node-challenge-api-service:latest
          ports:
            - containerPort: 3112
          env:
            - name: RMQ_URI
              value: amqp://rabbitmq-service:5672
          readinessProbe:
            tcpSocket:
              port: 3112
            initialDelaySeconds: 10
            periodSeconds: 5


---
apiVersion: v1
kind: Service
metadata:
  name: node-challenge-api-service
  labels:
    app: node-challenge-api-service
spec:
  type: NodePort
  selector:
    app: node-challenge-api-service
  ports:
    - protocol: TCP
      port: 3112
      targetPort: 3112
