apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-challenge-stock-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-challenge-stock-service
  template:
    metadata:
      labels:
        app: node-challenge-stock-service
    spec:
      containers:
        - name: node-challenge-stock-service
          image: localhost:31111/node-challenge-stock-service:latest
          ports:
            - containerPort: 3113
          env:
            - name: RMQ_URI
              value: amqp://rabbitmq-service:5672
          readinessProbe:
            tcpSocket:
              port: 3113
            initialDelaySeconds: 10
            periodSeconds: 5

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: stock-service
#  labels:
#    app: stock-service
#spec:
#  type: NodePort
#  selector:
#    app: stock-service
#  ports:
#    - protocol: TCP
#      port: 3113
#      targetPort: 3113